### ISSUE TITLE
Undefined index: clientId

### ISSUE THREAD

**Issue by FUGAMARU** [iPocketTeam/iPocketMine#5]
プラグインがクライアントIDを取得しようとするたびに画像のようなエラーが出ます。

画像↓
https://i.gyazo.com/708ec5dd644f3d6009eaa31cbffa9b39.png

**Comment by FUGAMARU** [comment]
ちなみにこれはKillBearBoysに限らず出るエラーですので、KillBearBoysのコード記述が問題ではないと思います。

**Comment by tomoMinecrafter** [comment]
修正済みの内容
